// packages/vue.channel/src/playground/app/App.vue
<template>
  <div>
    <div class="app">
      <Menu />
      <Content />
      <!-- <Content /> -->
      <Menu />
      <Content />
      <Left />
      <!-- <Content /> -->
    </div>
    <Devtool />
  </div>
</template>

<script lang="ts" setup>
// import Devtool from "../../lib/devtools/Devtool.vue";
import Devtool from "@channel-x/devtools/src/lib/Devtool.vue";
import Content from "./components/Content/Content.vue";
import Left from "./components/Left/Left.vue";
import Menu from "./components/Menu/Menu.vue";
</script>

<style scoped></style>

// packages/react.channel/src/App.tsx
// import Devtool from "@channel-x/devtools/src/lib/Devtool.vue";
import { useState } from 'react';
import './App.css';
import A from './components/A';
import B from './components/B';

// import "./remote-devtool.t.ts"
// const Devtool=React.lazy(() => import('remote_app/Devtool'))
//  console.log(Devtool)
function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <A/>
      <B/>
    </div>
  )
}

export default App
